<?
$aMenuLinks = Array(
	Array(
		"Калориферы", 
		"/teploobmennoe-oborudovanie/kalorifery/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Конденсаторы", 
		"/teploobmennoe-oborudovanie/kondensatory/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Компрессорно-конденсаторные блоки", 
		"/teploobmennoe-oborudovanie/kondensatbloki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Градирни", 
		"/teploobmennoe-oborudovanie/gradirni/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Воздухоохладители", 
		"/teploobmennoe-oborudovanie/vozduhookhladiteli/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>