<?
$aMenuLinks = Array(
	Array(
		"Рефрижераторы", 
		"/transportnyj-holod/refrizheratory/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Кондиционеры для коммерческого транспорта", 
		"/transportnyj-holod/konditcionery/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Кондиционеры для спецтехники", 
		"/transportnyj-holod/dlya-spetctekhniki/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Комплектующие", 
		"/transportnyj-holod/komplektuiushchie/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Дилеры", 
		"/transportnyj-holod/dilery/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>